name: realtime_client
description: Listens to changes in a PostgreSQL Database and via websockets. This is for usage with Supabase Realtime server.
version: 1.0.0-dev.1
homepage: 'https://supabase.io'
repository: 'https://github.com/supabase/realtime-dart'

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  web_socket_channel: ^2.1.0

dev_dependencies:
  lints: ^2.0.0
  mocktail: ^0.1.0
  test: ^1.16.5
